services:
  opcua-server:
    image: ghcr.io/andreasheine/sampleserver-node-opcua:main
    # ports:
    #   - 4840:4840
  opcua-client:
    image: opcua-client
    build:
      context: opcua-client
      dockerfile: ../opcua-client.Dockerfile
    ports:
      - 1880:1880
    environment:
      - FLOWS=/shared/flows.json
    volumes:
      # - ./opcua-client/data:/data:rw
      - ./opcua-client/flow:/shared:rw